### ISSUE TITLE
panic: interface conversion

### ISSUE THREAD

**Issue by Seirdy** [zerok/webmentiond#60]
My webmentiond has been repeatedly crashing with the following error logs:

```
Oct 03 19:15:03 webmentiond[2761311]: panic: interface conversion: interface {} is *microformats.Microformat, not string
Oct 03 19:15:03 webmentiond[2761311]: goroutine 15 [running]:
Oct 03 19:15:03 webmentiond[2761311]: github.com/zerok/webmentiond/pkg/webmention.mfFillMention(0xc0000ade38, 0xc0001ac680)
Oct 03 19:15:03 webmentiond[2761311]:         github.com/zerok/webmentiond/pkg/webmention/verify.go:213 +0x49d
Oct 03 19:15:03 webmentiond[2761311]: github.com/zerok/webmentiond/pkg/webmention.mfFillMention(0xc0000ade38, 0xc0001ac580)
Oct 03 19:15:03 webmentiond[2761311]:         github.com/zerok/webmentiond/pkg/webmention/verify.go:247 +0x4d7
Oct 03 19:15:03 webmentiond[2761311]: github.com/zerok/webmentiond/pkg/webmention.mfFillMentionFromData(...)
Oct 03 19:15:03 webmentiond[2761311]:         github.com/zerok/webmentiond/pkg/webmention/verify.go:206
Oct 03 19:15:03 webmentiond[2761311]: github.com/zerok/webmentiond/pkg/webmention.(*htmlVerifier).Verify(0xc0001d06c0?, {0x7fc250c34178, 0xc0001a0210}, 0x0?, {0x7fc229304c18, 0xc000206e40}, 0xc0000ade38)
Oct 03 19:15:03 webmentiond[2761311]:         github.com/zerok/webmentiond/pkg/webmention/verify.go:197 +0xd1f
Oct 03 19:15:03 webmentiond[2761311]: github.com/zerok/webmentiond/pkg/webmention.Verify({0x7fc250c34178, 0xc0001a0210}, 0xc00009fe38, {0xc000051d78, 0x1, 0xc000051dc8?})
Oct 03 19:15:03 webmentiond[2761311]:         github.com/zerok/webmentiond/pkg/webmention/verify.go:47 +0x22e
Oct 03 19:15:03 webmentiond[2761311]: github.com/zerok/webmentiond/pkg/server.(*Server).VerifyNextMention(0xc00017ec80, {0x7fc250c34178, 0xc0001a0210})
Oct 03 19:15:03 webmentiond[2761311]:         github.com/zerok/webmentiond/pkg/server/verify.go:42 +0x3bd
Oct 03 19:15:03 webmentiond[2761311]: github.com/zerok/webmentiond/pkg/server.(*Server).StartVerifier.func1()
Oct 03 19:15:03 webmentiond[2761311]:         github.com/zerok/webmentiond/pkg/server/verify.go:87 +0xdf
Oct 03 19:15:03 webmentiond[2761311]: created by github.com/zerok/webmentiond/pkg/server.(*Server).StartVerifier
Oct 03 19:15:03 webmentiond[2761311]:         github.com/zerok/webmentiond/pkg/server/verify.go:81 +0xd8
Oct 03 19:15:03 webmentiond.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Oct 03 19:15:03 webmentiond.service: Failed with result 'exit-code'.
```

It seems to be triggered by a markup parsing error.

**Comment by Seirdy** [comment]
Edited to show full log.

**Comment by zerok** [comment]
Hi :) Do you perhaps know which URL/document is causing this? Also: Could you please update your webmentiond instance and see if it works then?

**Comment by Seirdy** [comment]
Resolved out-of-band; [PEBCAK](https://en.wiktionary.org/wiki/PEBCAK). I was running the wrong (outdated) webmentiond build, thinking I was running a different one (latest commit). Thanks!
